### ISSUE TITLE
Textbox not showing PasswordChar if a text is setted on code

### ISSUE THREAD

**Issue by agausachs** [RJCodeAdvance/RJControls#1]
Hi! Thanks for your work! I think I found a bug on RJTextBox.cs

Steps to reproduce the issue:
- Put a RJTextbox on a form (rjtextbox1)
- Set PasswordChar property to True
- Set PlaceholderText to any string (like 'insert your password here')
- In your form constructor or in your form_Load event method, set a value to rjtextbox1, like rjtextbox.Texts = "My debug password".
- Compile and execute the app
- The textbox appears with the text "My debug password" totally readable (no char password). Be careful to set another control and set the focus to it before running the app, because if the rjtextbox1 has the focus just after runnig the app, it won't show any text.

**Comment by kotzer3** [comment]
i created a pullrequest ( #2 ) because i had similar problems.
handled it by following code: (manually set IsPlaceHolder property to false, when doing something with Texts property..)
```      
      this.rjTextBox1.IsPlaceHolder = false;
      this.rjTextBox1.Texts = "something";
```

**Comment by RJCodeAdvance** [comment]
I forgot to **remove the placeholde**r in the texts property (applies to both cases mentioned).
I updated the code.
    _public string Texts
    {
        get
        {
            if (isPlaceholder) return "";
            else return textBox1.Text;
        }
        set
        {
            **RemovePlaceholder();//If it is the case.**
            textBox1.Text = value;
            SetPlaceholder();//If it is the case.
        }
    }_
